id: P008171
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-17 13:05:53.252956
source_metadata:
  id: bdr:W1GS44056
  title: བོད་ཀྱི་རིག་གནས་ལོ་རྒྱུས་དཔྱད་གཞིའི་རྒྱུ་ཆ་བདམས་བསྒྲིགས་༔ ༢༡
  author: ''
  volumes:
    b115d8d3d3824648a39d7d0babc68ade:
      image_group_id: I5821
      title: ''
      volume_number: 1
      total_pages: 380
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
